"""moderndive: Python companion for ModernDive (Statistical Inference via Data Science).

Public API (mirrors the R ``moderndive`` + ``infer`` packages):

- ``specify`` — start an inference pipeline from a polars DataFrame
- ``get_confidence_interval``, ``get_p_value`` — summarize a distribution
- ``visualize``, ``shade_p_value``, ``shade_confidence_interval`` — plotnine layers
- ``get_regression_table``, ``get_regression_points``, ``tidy_summary`` — regression helpers
- ``rep_sample_n`` — repeated sampling from a population (sampling activities)
- ``theory`` — theory-based comparisons (scipy.stats wrappers)
- ``load_*`` — dataset loaders returning polars DataFrames
"""

from __future__ import annotations

from . import data as data
from . import theory as theory
from .data import available_datasets, load_dataset
from .data import __all__ as _data_all
from .infer import (
    assume,
    chisq_stat,
    chisq_test,
    get_ci,
    get_confidence_interval,
    get_p_value,
    get_pvalue,
    observe,
    prop_test,
    shade_ci,
    shade_confidence_interval,
    shade_p_value,
    shade_pvalue,
    specify,
    t_stat,
    t_test,
    visualise,
    visualize,
)
from .modeling import get_regression_points, get_regression_table, tidy_summary
from .plots import pairplot
from .sampling import rep_sample_n, rep_slice_sample

# Re-export every load_<name>() generated by the data module.
from .data import *  # noqa: F401,F403

__version__ = "0.1.0"

__all__ = [
    "specify",
    "observe",
    "assume",
    "get_confidence_interval",
    "get_p_value",
    "visualize",
    "shade_p_value",
    "shade_confidence_interval",
    "get_ci",
    "get_pvalue",
    "visualise",
    "shade_ci",
    "shade_pvalue",
    "t_test",
    "t_stat",
    "prop_test",
    "chisq_test",
    "chisq_stat",
    "get_regression_table",
    "get_regression_points",
    "tidy_summary",
    "pairplot",
    "rep_sample_n",
    "rep_slice_sample",
    "theory",
    "data",
    *_data_all,
]
