"""moderndive: Python companion for ModernDive (Statistical Inference via Data Science).

Public API (mirrors the R ``moderndive`` + ``infer`` packages):

- ``specify`` — start an inference pipeline from a polars DataFrame
- ``get_confidence_interval``, ``get_p_value`` — summarize a distribution
- ``visualize``, ``shade_p_value``, ``shade_confidence_interval`` — dual-engine plots
  (plotly by default, ``engine="plotnine"`` for the grammar-of-graphics objects)
- ``get_regression_table``, ``get_regression_points``, ``tidy_summary`` — regression helpers
- ``rep_sample_n`` — repeated sampling from a population (sampling activities)
- ``theory`` — theory-based comparisons (scipy.stats wrappers)
- ``load_*`` — dataset loaders returning polars DataFrames
"""

from __future__ import annotations

import sys

from . import data as data
from . import theory as theory
from .correlation import get_correlation, pop_sd

# Re-export every load_<name>() generated by the data module
# (available_datasets and load_dataset are included via the star import).
from .data import *  # noqa: F401,F403
from .data import __all__ as _data_all
from .infer import (
    assume,
    chisq_stat,
    chisq_test,
    get_ci,
    get_confidence_interval,
    get_p_value,
    get_pvalue,
    observe,
    prop_test,
    shade_ci,
    shade_confidence_interval,
    shade_p_value,
    shade_pvalue,
    specify,
    t_stat,
    t_test,
    visualise,
    visualize,
)
from .modeling import (
    count_missing,
    get_regression_points,
    get_regression_summaries,
    get_regression_table,
    tidy_summary,
)
from .plots import (
    geom_categorical_model,
    geom_parallel_slopes,
    gg_categorical_model,
    gg_parallel_slopes,
    pairplot,
)
from .sampling import rep_sample_n, rep_slice_sample

__version__ = "0.1.0"

__all__ = [
    "specify",
    "observe",
    "assume",
    "get_confidence_interval",
    "get_p_value",
    "visualize",
    "shade_p_value",
    "shade_confidence_interval",
    "get_ci",
    "get_pvalue",
    "visualise",
    "shade_ci",
    "shade_pvalue",
    "t_test",
    "t_stat",
    "prop_test",
    "chisq_test",
    "chisq_stat",
    "get_regression_table",
    "get_regression_points",
    "get_regression_summaries",
    "get_correlation",
    "pop_sd",
    "tidy_summary",
    "count_missing",
    "pairplot",
    "gg_parallel_slopes",
    "geom_parallel_slopes",
    "gg_categorical_model",
    "geom_categorical_model",
    "rep_sample_n",
    "rep_slice_sample",
    "theory",
    "data",
    *_data_all,
]


def _png_to_html_img(png) -> str | None:
    """Wrap a PNG (raw bytes or base64 str) in an ``<img>`` data-URI tag."""
    if not png:
        return None
    if isinstance(png, (bytes, bytearray)):
        import base64

        png = base64.b64encode(png).decode()
    return f'<img src="data:image/png;base64,{png}" style="max-width:100%;height:auto;">'


def _apply_pyodide_shims():
    """Patch polars and plotnine for Pyodide's WebAssembly build.

    Two gaps break in-browser interactive cells:

    1. Pyodide's ``polars`` build has no Parquet IO and its Arrow/pandas export
       panics, which breaks the dataset loaders (``load_*``) and any
       ``.to_pandas()`` call (e.g. feeding a plotnine plot). Route Parquet reads
       through ``pyarrow`` and ``to_pandas`` through a dict round-trip.
    2. A plotnine ``ggplot`` exposes its rendered image only via
       ``_repr_mimebundle_`` (which returns a ``(data, metadata)`` tuple), but
       quarto-live renders results through ``_repr_html_``/``_repr_png_`` — so
       ggplot plots show blank. Give ``ggplot`` a ``_repr_html_`` that embeds the
       PNG, which also fixes ``InferPlot`` (it delegates to the figure).

    Applied automatically under Pyodide; a no-op on a normal install.
    """
    import polars as pl

    def _read_parquet(source, *args, **kwargs):
        import pyarrow.parquet as pq

        return pl.from_arrow(pq.read_table(source))

    def _scan_parquet(source, *args, **kwargs):
        import pyarrow.parquet as pq

        return pl.from_arrow(pq.read_table(source)).lazy()

    def _to_pandas(self, *args, **kwargs):
        import pandas as pd

        return pd.DataFrame(self.to_dict(as_series=False))

    pl.read_parquet = _read_parquet
    pl.scan_parquet = _scan_parquet
    pl.DataFrame.to_pandas = _to_pandas

    from plotnine import ggplot

    def _ggplot_repr_html(self):
        bundle = self._repr_mimebundle_()
        data = bundle[0] if isinstance(bundle, tuple) else bundle
        png = data.get("image/png") if isinstance(data, dict) else None
        return _png_to_html_img(png)

    ggplot._repr_html_ = _ggplot_repr_html


if sys.platform == "emscripten":  # pragma: no cover - only runs under Pyodide
    _apply_pyodide_shims()
